apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
