apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: simple-rabbitmq
  template:
    metadata:
      labels:
        app: simple-rabbitmq
    spec:
      containers:
      - name: simple-rabbitmq
        image: rabbitmq:3-management
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: amqp
            containerPort: 5672
            protocol: TCP
          - name: http
            containerPort: 15672
            protocol: TCP
        env:
          - name: RABBITMQ_ERLANG_COOKIE
            value: "SWQOKODSQALRPCLNMEQG"
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
          - name: RABBITMQ_DEFAULT_PASS
            value: "guest"
          - name: RABBITMQ_DEFAULT_VHOST
            value: "/"
---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
      app: rabbitmq-service
spec:
  selector:
    app: simple-rabbitmq    
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 15672
      nodePort: 30091
    - name: amqp
      protocol: TCP
      port: 5672
      nodePort: 30092