version: '3.7'

services:
  messages-publisher:
    image: alanbarros/msg.publisher:{Build.BuildId}
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.labels.web == true
        update_config:
          order: start-first
        labels:
          - "traefik.http.routers.mensagens.rule=PathPrefix(`/mensagens`)"            
          - "traefik.http.routers.mensagens.service=mensagens" # <-----
          - "traefik.http.routers.mensagens.middlewares=mensagensMid" # <-----
          - "traefik.http.services.mensagens.loadbalancer.server.port=80"
          - "traefik.http.middlewares.mensagensMid.stripprefix.prefixes=/mensagens"
          - "traefik.docker.lbswarm=true"
          - "traefik.enable=true"
          - "traefik.port=80"

    networks: 
      - messages-network

  messages-listener:
    image: alanbarros/msg.listener:{Build.BuildId}
    networks: 
    - messages-network

  messages-listener2:
    image: alanbarros/msg.listener:{Build.BuildId}
    networks: 
    - messages-network

networks:
  messages-network: 