version: '3.7'

services:
  messages-publisher:
    image: alanbarros/msg.publisher
    container_name: publisher
    build:
      context: .
      dockerfile: messages-publisher/Dockerfile
      target: final
    networks: 
      - messages-network

  messages-listener:
    image: alanbarros/msg.listener
    container_name: listener
    build: 
      context: .
      dockerfile: messages-listener/Dockerfile
    networks: 
    - messages-network

networks:
  messages-network: 